### ISSUE TITLE
Feature Request: button to show/hide all annotations

### ISSUE THREAD

**Issue by spaceof7** [jeremyk6/annotationManager#2]
I'd find this really useful instead of toggling them all individually.  The Ctrl-T keyboard shortcut to toggle all annotations has the drawback of just toggling the annotations, not show/hide all annotations.  Also it requires that the annotation tool is selected which adds a step for me.

**Comment by jeremyk6** [comment]
Added in https://github.com/jeremyk6/annotationManager/commit/65ba22fcc40a2bbaa6d6e28d41d5465c5c158b80 .
